---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Digital.ai - Official/Workflows/Digital.ai Deploy
spec:
- template: Azure Application setup with Digital.ai Deploy to create Azure resource
    groups
  description: "Seamless create an application in Digital.ai Deploy that can create\
    \ Azure resource groups, including its respective environment and infrastructure\
    \ setup."
  scheduledStartDate: 2023-03-23T09:00:00+05:30
  dueDate: 2023-03-23T10:00:00+05:30
  kind: WORKFLOW
  phases:
  - phase: Setup Infra and Env
    tasks:
    - name: Specify Deploy Server Details
      type: xlrelease.UserInputTask
      description: Select the Deploy Server Connection onto which the Azure application
        has to be created. You can create a new connection if you have not created
        one.
      owner: admin
      variables:
      - deploy-server
    - name: Specify Environment Name
      type: xlrelease.UserInputTask
      description: Please enter the required information below.
      owner: admin
      variables:
      - environment-name
    - name: Create Environment
      type: deploy.CreateCI
      owner: admin
      variableMapping:
        server: "${deploy-server}"
      capabilities:
      - remote
      ciID: "Environments/${environment-name}"
      ciType: udm.Environment
      jsonDescriptor: "{}"
    - name: Specify Azure Connection Parameters
      type: xlrelease.UserInputTask
      description: Please enter the required information below.
      owner: admin
      variables:
      - azurecloud-identifier
      - subscription-id
      - tenant-id
      - client-id
      - client-secret
    - name: Configure Azure Connection
      type: deploy.CreateCI
      owner: admin
      variableMapping:
        server: "${deploy-server}"
      capabilities:
      - remote
      ciID: "Infrastructure/${azurecloud-identifier}"
      ciType: azure.Cloud
      jsonDescriptor: |-
        {
            "authMethod":"directory-application-and-service-principal",
            "subscriptionId":"${subscription-id}",
            "tenantId":"${tenant-id}",
            "clientId":"${client-id}",
            "clientKey":"${client-secret}"
        }
      addToEnvironment: true
      envID: "Environments/${environment-name}"
    - name: Check Azure Connection
      type: deploy.ControlTask
      owner: admin
      variableMapping:
        server: "${deploy-server}"
      capabilities:
      - remote
      ciId: "Infrastructure/${azurecloud-identifier}"
      taskName: checkConnection
      numberOfContinueRetrials: 0
      pollingInterval: 10
      numberOfPollingTrials: 0
      displayStepLogs: true
      connectionRetries: 10
    color: '#3d6c9e'
  - phase: Setup Application
    tasks:
    - name: Specify Application Name
      type: xlrelease.UserInputTask
      description: Please enter the required information below.
      owner: admin
      variables:
      - application-name
    - name: Create Application
      type: deploy.CreateCI
      owner: admin
      variableMapping:
        server: "${deploy-server}"
      capabilities:
      - remote
      ciID: "Applications/${application-name}"
      ciType: udm.Application
      jsonDescriptor: "{}"
    - name: Specify Package Name
      type: xlrelease.UserInputTask
      description: Please enter the required information below.
      owner: admin
      variables:
      - package-name
    - name: Create Deployment Package
      type: deploy.CreateCI
      owner: admin
      variableMapping:
        server: "${deploy-server}"
      capabilities:
      - remote
      ciID: "Applications/${application-name}/${package-name}"
      ciType: udm.DeploymentPackage
      jsonDescriptor: "{}"
    - name: Specify Resource Group Parameters
      type: xlrelease.UserInputTask
      description: Please enter the required information below.
      owner: admin
      variables:
      - resourcegroup-name
      - resourcegroup-location
    - name: Create Sample Resource Group
      type: deploy.CreateCI
      owner: admin
      variableMapping:
        server: "${deploy-server}"
      capabilities:
      - remote
      ciID: "Applications/${application-name}/${package-name}/sample-resource-group"
      ciType: azure.ResourceGroupSpec
      jsonDescriptor: |-
        {
            "location":"${resourcegroup-location}",
            "resourceGroupName":"${resourcegroup-name}"
        }
    - name: Add Managed Application
      type: xlrelease.ScriptTask
      owner: admin
      script: |-
        from com.xebialabs.xlrelease.api.v1.views import ManagedApplicationView
        from com.xebialabs.xlrelease.api.v1.views import ConnectionServerView
        from java.util import Date
        from java.text import SimpleDateFormat
        import datetime

        parsedDate = datetime.datetime.now()

        requestBody = ManagedApplicationView()
        requestBody.applicationName = "${application-name}"
        requestBody.managedBy = "Digital.ai Deploy"
        requestBody.dateCreated = parsedDate
        requestBody.environmentTag = "${environment-name}"
        requestBody.applicationReference = "${application-name}"

        connectionServer = ConnectionServerView('${deploy-server}', '', '', '')
        requestBody.connectionServer = connectionServer

        res = managedApplicationApi.addManagedApplication(requestBody)
    color: '#3d6c9e'
  categories:
  - Application onboarding
  variables:
  - type: xlrelease.StringVariable
    key: environment-name
    value: azure-env
  - type: xlrelease.StringVariable
    key: application-name
    value: azure-app
  - type: xlrelease.StringVariable
    key: package-name
    value: "1.0"
  - type: xlrelease.StringVariable
    key: azurecloud-identifier
    value: azure-cloud
  - type: xlrelease.StringVariable
    key: client-id
    value: client-id
  - type: xlrelease.StringVariable
    key: client-secret
    value: client-secret
  - type: xlrelease.StringVariable
    key: subscription-id
    value: subscription-id
  - type: xlrelease.StringVariable
    key: tenant-id
    value: tenant-id
  - type: xlrelease.StringVariable
    key: resourcegroup-location
    value: East US
  - type: xlrelease.StringVariable
    key: resourcegroup-name
    value: resourcegroup-name
  - type: xlrelease.ReferenceVariable
    key: deploy-server
    showOnReleaseStart: false
    label: Deploy Server
    referencedType: digitalai.DeployServer
  author: Digital.ai
  logo:
    type: xlrelease.TemplateLogo
    contentType: image/svg+xml
    file: !file "template-logo/xlr-xld-plugin.svg"
  defaultTargetFolder: Digital.ai - Official/Workflow Executions
